### PR TITLE
unify network and shared memory modes.

### PR DESCRIPTION
**Pull request by accumulator**
Only for pulseaudio clients in this patch. The aim is to deduplicate
code, so it's better to unify the output drivers as well in the future
instead of duplicating these changes to the alsa and raw variants.

The patch splits off the initialization and audio data transfer for both
receive methods and generalizes access to the audio data and stream
properties so that they're receiver encoding independent.

The main loop simply calls receiver_rcv_fn, a function pointer to a
specific receiver implementation, which fills the supplied receiver_data
structure with audio data and the stream properties. The rest of the main
loop can then control the output driver from this data.

### CODE REVIEW

**Comment by accumulator** [comment]
As said in the commit message, this is only done for pulseaudio output driver. 
I wanted to get your feedback first before attempting to unify the output drivers into one as well (this probably needs some build system like CMake, otherwise ppl will probably scream (pun intended) when e.g. pulseaudio is not an optional dependency)

**Comment by accumulator** [comment]
oh two more remarks:

There's no extra copying of audio data done, so performance is not impacted

And sorry for the big delta, git didn't recognize scream-pulse.c was changed, so it recorded it as a delete + new file :(

**Comment by duncanthrax** [comment]
That is a much-needed refactoring. The number of receivers grew over time, and copying the code was non-invasive for existing receivers ... but as you noticed, adding general improvements was getting cumbersome.

Thanks for this! :)

**Comment by martinellimarco** [comment]
Good job @accumulator, this was needed.

May I suggest that we add a note about this change in the main README? I know there are a few tutorials out there that explain how to setup these receivers, including the [arch wiki](https://wiki.archlinux.org/index.php/PCI_passthrough_via_OVMF#Passing_VM_audio_to_host_via_Scream), and users may get confused now that the binary have a different name.

Also we should update the last paragraph that still have the old binary name.

**Comment by accumulator** [comment]
Wow, didn't expect this change to be merged already :)
I'm progressing a bit on unifying the outputs too, but I'll open another PR for that.

**Pull request merged**
