### PR TITLE
Patch for IVSHMEM support

### PR DESCRIPTION
**Pull request by martinellimarco**
Hi @duncanthrax , here's the patch for #36 

So far I've tested on multiple VMs and it seems to work fine.
I think it's best to wait for others to test this before you merge it.
Please tell me if there is anything you'd like to change. I'm open to constructive critiques.

Instructions for the end users:

### How to use

Add a new IVSHMEM device to your VM. I reccomand using the same domain and bus that looking glass use, but with an higher slot number. If you don't use looking glass it doesn't matter where you attach your device.

The size can be any power of 2, it's an IVSHMEM requirement. 1MiB is more than enough in most cases. If you use higher settings like 192000Hz, 32bit, 8channels then you may want to increase it to 2 or 4 MiB, but it's not necessary.

As example:
```
    <shmem name='scream-ivshmem'>
      <model type='ivshmem-plain'/>
      <size unit='M'>1</size>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x11' function='0x0'/>
    </shmem>
```

Launch the VM and check that the shared memory is created under `/dev/shm/`. Also check that you have read permissions.

On linux, compile pulseaudio-ivshmem with `make` then run it with `scream-ivshmem-pulse  /dev/shm/scream-ivshmem`.

On windows, open `regedit` and add a DWORD named `UseIVSHMEM` in `HKLM\SYSTEM\CurrentControlSet\Services\Scream\Options`.

The value of this option MUST match the size in MiB of the IVSHMEM device you want to use.

Install the driver or reboot if you had already installed it.

### CODE REVIEW

**Comment by martinellimarco** [comment]
Hi again @duncanthrax . I've added the ivshmem-alsa receiver. Soon I'll send the ivshmem-raw receiver.

On a side note, did you get my email about your invitation to contribute to this project?

**Comment by duncanthrax** [comment]
Hi Marco,

I'm out until Friday. Didn't get an email so far! Which address did you send it to?

**Comment by martinellimarco** [comment]
Hi Tom,

I wrote to tom@duncanthrax.net  It's a shame that GitHub doesn't offer a way to exchange private messages.

To sum it up, I wanted to make sure that you giving me the contributor status wasn't an error. In the email I also thanked you for the trust showed and I wrote that I'd like to help with this project but I don't feel I have the right to merge pull requests without your approval because in the end this is your project and you should have the final say.

In practice, if it wasn't a mistake and you are ok with it I'll help fix the occasional bugs, contribute to close the existing issues and submit new contributions for you to review and approve.

**Comment by martinellimarco** [comment]
Hi Tom,
as discussed in my last email I've pushed the raw-ivshmem receiver.
When you have time you can proceed to sign the driver and release it.
All the feedback from the testers in issue #36 are positive so far so I think it's safe to do so.

Thank you

**Pull request merged**
