### PR TITLE
More unify

### PR DESCRIPTION
**Pull request by accumulator**
I went ahead and unified pulseaudio and raw in a single executable.
ALSA should not be too difficult, but isn't moved yet.

Please test, since I didn't test all combinations of receiver and output

### CODE REVIEW

**Comment by martinellimarco** [comment]
I like the way this is turning out, good job. I'll made sure to test it later today.

 Maybe linux is not the best choice for the folder name because the pulseaudio receiver works on any platform where pulseaudio works, including bsd and mac os (in theory even windows)

I know from previous bug reports that at least a few users use the receiver on mac os, it's worth checking if it still compile and works there too.

I also think that we should be aware that we are introducing a breaking change renaming binaries and changing command line parameters for users and package maintainers. For an example of such packages see issue #77

I know I've already mentioned this in #76 but I think it's important to clarify in our README.md that we are changing things to not confuse end users.

**Comment by accumulator** [comment]
ALSA is now moved too, and I changed the folder name from linux/ to unix/.

I did notice underruns happening on ALSA using the defaults, but I see the same behaviour with the old client. Maybe my machine.. Upping the latency fixes the issue. Maybe setting a higher default would be smart.

**Comment by accumulator** [comment]
I think the changes could be described in the Changelog/Release Notes when a new release is made.

**Comment by accumulator** [comment]
Great. Works as well on my debian bullseye

**Comment by martinellimarco** [comment]
I've tested the network version too, both alsa and pulse (both linux and osx) and as far as I can tell everything is working as expected. Good job.

If @duncanthrax doesn't have anything to add I think this can be merged safely.

**Comment by duncanthrax** [comment]
Great work, thank you guys.

There are no binary releases for the receivers, so I'll just update the README to reflect the new state.

**Comment by DarthGandalf** [comment]
Hi, can you do a new release with these changes?

**Comment by accumulator** [comment]
> Hi, can you do a new release with these changes?

I agree. If only just a tag on current master, that would help distributions pin on a known good version.

**Comment by duncanthrax** [comment]
I get the point. Not yet sure if I add a release branch or just make a "blind" new release of the driver to let github create a new tag ...

**Pull request merged**
